// src/data/help_glossary.ts
// Justification: Comprehensive enterprise governance dictionary for mouse-over overlay help.

import { GlossaryTerm } from '../types/config.js';

export const HELP_GLOSSARY: GlossaryTerm[] = [
  {
    id: 'lob',
    term: 'LOB (Line of Business)',
    aliases: ['lob', 'line of business', 'division', 'operating unit'],
    category: 'Enterprise Structure',
    shortDefinition: 'An operating division or corporate subsidiary of Upbound Group, Inc.',
    detailedExplanation:
      'Upbound Group operates multiple omni-channel financial technology brands. Each Line of Business has distinct customer profiles, statutory jurisdictions, credit underwriting processes, and risk profiles for citizen development automations.',
    upboundContext:
      'Includes Acima (fintech merchant lease-to-own), Rent-A-Center (brick-and-mortar retail leases), Brigit (financial wellness & cash advances), Corporate (shared platform & strategy), and Mexico (international operations).',
    governanceImplication:
      'Automations in one LOB cannot inadvertently access or mix consumer data from another without formal cross-entity Data Protection Addendums.',
    regulatoryReference: 'GLBA 15 U.S.C. § 6801 (Safeguards Rule)',
  },
  {
    id: 'governed',
    term: 'Governed Workflow',
    aliases: ['governed', 'governed low', 'governed workflows', 'tier 1 governed'],
    category: 'Governance Tier',
    shortDefinition:
      'An automation formally registered in ServiceNow CMDB with verified compliance controls.',
    detailedExplanation:
      'A governed workflow has passed algorithmic tiering or human GRC review, is bound to an identified employee owner, adheres to zero-PII restrictions, and participates in automated 90-day periodic reattestation.',
    upboundContext:
      'Represents our primary enterprise metric: converting unmonitored "Shadow IT" AI into auditable, approved business capabilities.',
    governanceImplication:
      'Permits citizen developer execution without blocking velocity while providing complete audit defensibility.',
    regulatoryReference: 'ISO/IEC 42001:2023 Clause 8.2 & NIST AI RMF GOVERN 1.2',
  },
  {
    id: 'tier4',
    term: 'Tier 4 Prohibited',
    aliases: ['tier 4', 'prohibited', 'banned', 'tier 4 prohibited'],
    category: 'Governance Tier',
    shortDefinition:
      'High-risk or legally non-compliant automation categorically prohibited from citizen developer execution.',
    detailedExplanation:
      'Any workflow that attempts autonomous credit underwriting, lease approvals, automated debt collection outreach, or ingests production payment credentials without human oversight. Prohibited workflows are automatically blocked.',
    upboundContext:
      'In consumer leasing (Acima & Rent-A-Center), black-box AI decisions that decline customer leases violate adverse action notice requirements.',
    governanceImplication:
      'Citizen developers are prohibited from building or deploying these automations. Must be routed to central Enterprise Data Science with full model validation.',
    regulatoryReference: 'CFPB Circular 2022-03, ECOA / Regulation B (12 CFR § 1002.9)',
  },
  {
    id: 'tier3',
    term: 'Tier 3 High Risk',
    aliases: ['tier 3', 'high risk', 'tier 3 high risk'],
    category: 'Governance Tier',
    shortDefinition:
      'Automations touching customer financial data, customer communications, or core financial operations.',
    detailedExplanation:
      'These workflows involve customer PII, account balances, payment history, or generate outbound communications sent directly to customers. They require explicit dual sign-off from InfoSec and Legal before deployment.',
    upboundContext:
      'Example: An automated customer email summary generated by Claude or ChatGPT. Requires human review before transmission.',
    governanceImplication:
      'Mandatory Human-in-the-Loop (HITL) review and verified Enterprise Zero Data Retention tenant model.',
    regulatoryReference: 'EU AI Act Article 14 (Human Oversight) & NIST AI 100-1 MANAGE 2.4',
  },
  {
    id: 'tier2',
    term: 'Tier 2 Moderate Risk',
    aliases: ['tier 2', 'moderate risk', 'tier 2 moderate'],
    category: 'Governance Tier',
    shortDefinition:
      'Automations handling internal confidential business information or broad employee workflows.',
    detailedExplanation:
      'Workflows that process company strategy, internal financial reporting drafts, operational guidelines, or team-wide documentation. Subject to review and approval by the designated AI Program Lead.',
    upboundContext:
      'Example: Regional store operations summaries, intranet HR onboarding guides, or competitive analysis decks.',
    governanceImplication:
      'Approved conditionally with access control boundaries; no customer bank or SSN records permitted.',
    regulatoryReference: 'ISO/IEC 42001:2023 Clause 6.1 (Risk Assessment)',
  },
  {
    id: 'tier1',
    term: 'Tier 1 Governed (Low Risk)',
    aliases: ['tier 1', 'low risk', 'tier 1 low', 'personal productivity'],
    category: 'Governance Tier',
    shortDefinition: 'Personal productivity automations operating strictly on public or non-sensitive data.',
    detailedExplanation:
      'Workflows utilizing company-approved AI tools (e.g. Copilot, Claude Enterprise) for individual drafting, code syntax assistance, or public research. Automatically approved upon registration.',
    upboundContext:
      'Encourages workforce AI adoption and skill growth without bureaucratic friction for safe everyday tasks.',
    governanceImplication: 'Auto-approved instantly upon intake submission; reattested annually.',
    regulatoryReference: 'NIST AI RMF MAP 1.1',
  },
  {
    id: 'shadow_it',
    term: 'Shadow IT Exposure Gap',
    aliases: ['shadow it', 'unregistered', 'exposure gap', 'unregistered seats'],
    category: 'Risk & Compliance',
    shortDefinition:
      'The estimated gap between formally registered AI workflows and active AI tool user licenses.',
    detailedExplanation:
      'By comparing corporate SSO identity logs for approved AI tools against the ServiceNow workflow registry, we estimate approximately 142 unregistered automations operating without formal review across Upbound divisions.',
    upboundContext:
      'Our primary objective is to make registration so fast (under 3 minutes) that employees willingly register rather than hiding their automations.',
    governanceImplication:
      'Unregistered automations pose severe prompt leakage, IP infringement, and compliance audit failure risks.',
    regulatoryReference: 'ISO 27001:2022 Control A.5.8 (Information Security in Project Management)',
  },
  {
    id: 'iso42001',
    term: 'ISO/IEC 42001:2023 (AIMS)',
    aliases: ['iso 42001', 'aims', 'iso/iec 42001', 'plan-do-check-act'],
    category: 'Regulatory Standard',
    shortDefinition:
      'The international certifiable management standard for Artificial Intelligence Management Systems.',
    detailedExplanation:
      'Follows the Plan-Do-Check-Act (PDCA) management system structure. Requires documented policies, risk assessments, Clause 7.2 (competence verification), and Clause 7.3 (awareness across all AI practitioners).',
    upboundContext:
      'Upbound Group benchmarks its Citizen Developer Registry directly against ISO 42001 Annex A controls to achieve external certification readiness.',
    governanceImplication:
      'Certifiable proof to enterprise partners and retail merchants that AI deployed across our platforms is governed.',
    regulatoryReference: 'ISO/IEC 42001:2023 Clauses 4 through 10',
  },
  {
    id: 'nist_rmf',
    term: 'NIST AI RMF 1.0 (NIST AI 100-1)',
    aliases: ['nist', 'nist ai rmf', 'rmf', 'govern-map-measure-manage'],
    category: 'Regulatory Standard',
    shortDefinition: 'U.S. National Institute of Standards voluntary taxonomy for managing AI risks.',
    detailedExplanation:
      'Organized into four core functions: GOVERN (culture & accountability), MAP (context & categorization), MEASURE (quantitative assessment), and MANAGE (allocation of risk resources).',
    upboundContext:
      'Our risk engine operationalizes the MAP and MEASURE functions to score every citizen workflow into deterministic governance tiers.',
    governanceImplication:
      'Provides defensible federal alignment against FTC and Department of Commerce enforcement standards.',
    regulatoryReference: 'NIST Special Publication AI 100-1',
  },
  {
    id: 'cfpb_regb',
    term: 'CFPB Regulation B / ECOA',
    aliases: ['cfpb', 'regulation b', 'reg b', 'ecoa', 'adverse action'],
    category: 'Regulatory Standard',
    shortDefinition:
      'Equal Credit Opportunity Act statutory requirements prohibiting algorithmic bias and requiring explainable adverse action.',
    detailedExplanation:
      'When a consumer is denied credit or a lease agreement, the creditor must provide specific, principal reasons for the denial. Creditors cannot justify opacity by claiming an AI model is too complex or a third-party black box.',
    upboundContext:
      'Directly dictates why automated underwriting by citizen developers is strictly classified as Tier 4 Prohibited.',
    governanceImplication:
      'Violations incur severe civil money penalties and public enforcement consent orders from the Consumer Financial Protection Bureau.',
    regulatoryReference: '12 CFR § 1002.9; CFPB Circular 2022-03',
  },
  {
    id: 'eu_ai_act',
    term: 'EU AI Act (Article 4 Literacy)',
    aliases: ['eu ai act', 'ai literacy', 'article 4', 'article 50'],
    category: 'Regulatory Standard',
    shortDefinition:
      'Statutory regulation mandating workforce AI literacy and risk classification across organizations.',
    detailedExplanation:
      'Article 4 took effect in February 2025, legally requiring employers to ensure staff operating AI systems possess an adequate level of AI literacy. Article 50 enforces transparency for synthetic media and AI-generated text.',
    upboundContext:
      'Operationalized via our companion Acceptable Use Knowledge Check and 5-axis polar literacy radar across divisions.',
    governanceImplication:
      'Mandatory prerequisite: citizen developers must maintain current AI training status to register active automations.',
    regulatoryReference: 'EU Regulation 2024/1689, Articles 4, 14 & 50',
  },
  {
    id: 'servicenow',
    term: 'ServiceNow CMDB Integration',
    aliases: ['servicenow', 'cmdb', 'u_ai_workflow_registry', 'record producer'],
    category: 'Architecture',
    shortDefinition: 'The enterprise system of record where production AI workflow data models reside.',
    detailedExplanation:
      'Our prototype mirrors the `u_ai_workflow_registry` table in ServiceNow CMDB, utilizing Record Producers for 4-step intake, Flow Designer for Tier 2/3 approval routings, and SLA engines for 90-day reattestation.',
    upboundContext:
      'Eliminates duplicate software investments by leveraging Upbound Group’s existing ServiceNow IT Service Management infrastructure.',
    governanceImplication:
      'Ensures every AI automation is linked to employee HR records, IT assets, and vendor software contracts.',
    regulatoryReference: 'ServiceNow IT Service Management & GRC Module',
  },
  {
    id: 'zero_data_retention',
    term: 'Zero Data Retention (ZDR)',
    aliases: ['zero data retention', 'zdr', 'model training opt-out', 'no training'],
    category: 'Risk & Compliance',
    shortDefinition:
      'Contractual guarantee from AI vendors that user prompts are never stored or used to train future models.',
    detailedExplanation:
      'Under standard consumer AI terms (e.g. free ChatGPT), user prompts may be logged and used to retrain foundation models. Enterprise ZDR agreements legally bind vendors to discard inputs immediately after generating an inference.',
    upboundContext:
      'Required for all tools approved for Tier 2 and Tier 3 workflows to prevent Samsung-style intellectual property leakage.',
    governanceImplication:
      'Tools without verified ZDR are declined or restricted strictly to public, non-sensitive data.',
    regulatoryReference: 'SOC 2 Type II Confidentiality & Privacy Criteria',
  },
  {
    id: 'hitl',
    term: 'Human-in-the-Loop (HITL)',
    aliases: ['hitl', 'human in the loop', 'human oversight', 'human review'],
    category: 'Governance Tier',
    shortDefinition:
      'Mandatory human verification and sign-off before AI-generated outputs affect external parties or business operations.',
    detailedExplanation:
      'Ensures that autonomous agents do not directly execute critical financial transactions, send communications to customers, or update credit files without a human supervisor reviewing and approving the result.',
    upboundContext:
      'Enforced on all Tier 3 and conditional Tier 2 automations across Acima, Rent-A-Center, and Brigit.',
    governanceImplication:
      'Mitigates confabulation/hallucination liability and satisfies statutory regulatory human oversight directives.',
    regulatoryReference: 'EU AI Act Article 14; NIST AI RMF MANAGE 2.4',
  },
  {
    id: 'acima',
    term: 'Acima',
    aliases: ['acima', 'acima leasing'],
    category: 'Enterprise Structure',
    shortDefinition: 'Upbound Group’s merchant fintech lease-to-own technology brand.',
    detailedExplanation:
      'Provides point-of-sale and e-commerce lease financing at thousands of retail partners across the United States. High transaction velocity, automated underwriting algorithms, and digital consumer onboarding.',
    upboundContext:
      'Largest volume of citizen developer automations in analytics, underwriting scripts, and retail partner communications.',
    governanceImplication: 'Strict credit scoring and FCRA/ECOA adverse action compliance controls required.',
    regulatoryReference: 'FCRA 15 U.S.C. § 1681; ECOA 15 U.S.C. § 1691',
  },
  {
    id: 'rac',
    term: 'Rent-A-Center (RAC)',
    aliases: ['rac', 'rent-a-center', 'rent a center'],
    category: 'Enterprise Structure',
    shortDefinition:
      'Upbound Group’s legacy brick-and-mortar retail brand operating hundreds of corporate stores nationwide.',
    detailedExplanation:
      'Direct customer leasing of furniture, electronics, appliances, and computers. Features regional field store managers, store associate training, and local retail delivery operations.',
    upboundContext:
      'Citizen automations focus on bilingual store signage, regional operations reporting, inventory tracking, and customer service.',
    governanceImplication:
      'In-store customer interactions must protect customer PII and avoid unverified meeting audio recordings.',
    regulatoryReference: 'FTC Safeguards Rule 16 CFR Part 314',
  },
  {
    id: 'brigit',
    term: 'Brigit',
    aliases: ['brigit', 'brigit wellness'],
    category: 'Enterprise Structure',
    shortDefinition: 'Upbound Group’s consumer financial health and cash-advance subscription application.',
    detailedExplanation:
      'Offers budget forecasting, credit monitoring, identity theft protection, and small-dollar cash advances to help working Americans manage financial wellness.',
    upboundContext:
      'Automations primarily support user onboarding, support ticket routing, and financial literacy content synthesis.',
    governanceImplication:
      'Direct access to consumer bank transaction feeds mandates strict GLBA financial privacy controls.',
    regulatoryReference: 'Gramm-Leach-Bliley Act (GLBA) Privacy Rule',
  },
];

/**
 * Helper to look up a term by word or element text
 */
export function findGlossaryTerm(query: string): GlossaryTerm | null {
  if (!query || typeof query !== 'string') return null;
  const clean = query.trim().toLowerCase();

  // 1. Exact match on term or alias
  for (const item of HELP_GLOSSARY) {
    if (item.term.toLowerCase() === clean || item.id === clean) return item;
    if (item.aliases.some((a) => a === clean)) return item;
  }

  // 2. Substring match
  for (const item of HELP_GLOSSARY) {
    if (clean.includes(item.id)) return item;
    if (item.aliases.some((a) => clean.includes(a))) return item;
  }

  return null;
}
